### ISSUE TITLE
Server side error exception: loot table problem?

### ISSUE THREAD

**Issue by MJRamon** [TheMillman/ChristmasFestivity#2]
```
[26дек2020 01:03:35.802] [Worker-Main-8/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 8
	Listeners:
		0: NORMAL
		1: ASM: class net.silentchaos512.endertendril.setup.LootInjector onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		2: net.minecraftforge.eventbus.EventBus$$Lambda$2709/1161119509@579a26da
		3: ASM: com.chrisgli.gemsnjewels.Main@38e93a04 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		4: ASM: class com.criobite.joshxmas.XMasForgeEvents lootTablesLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		5: ASM: class artifacts.common.init.LootTables$LootTableEvents onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		6: ASM: class blueduck.jollyboxes.util.LootUtil$LootEvents onLootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		7: ASM: class vectorwing.farmersdelight.setup.CommonEventHandler onLootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		8: ASM: class com.the_millman.christmasfestivity.event.LootHandler lootLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		9: ASM: class com.github.alexthe666.rats.server.events.CommonEvents onLootTableRolled(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		10: ASM: vazkii.quark.content.tools.module.AncientTomesModule@a0ff915 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		11: ASM: vazkii.quark.content.tools.module.ColorRunesModule@7905a559 onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
		12: LOWEST
		13: ASM: class com.minecraftabnormals.abnormals_core.core.registry.LootInjectionRegistry onLootTableLoad(Lnet/minecraftforge/event/LootTableLoadEvent;)V
java.lang.NullPointerException
	at net.minecraft.loot.LootTable.lambda$addPool$2(LootTable.java:207)
	at java.util.stream.MatchOps$1MatchSink.accept(Unknown Source)
	at java.util.ArrayList$ArrayListSpliterator.tryAdvance(Unknown Source)
	at java.util.stream.ReferencePipeline.forEachWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(Unknown Source)
	at java.util.stream.AbstractPipeline.copyInto(Unknown Source)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(Unknown Source)
	at java.util.stream.AbstractPipeline.evaluate(Unknown Source)
	at java.util.stream.ReferencePipeline.anyMatch(Unknown Source)
	at net.minecraft.loot.LootTable.addPool(LootTable.java:207)
	at com.the_millman.christmasfestivity.event.LootHandler.lootLoad(LootHandler.java:30)
	at net.minecraftforge.eventbus.ASMEventHandler_385_LootHandler_lootLoad_LootTableLoadEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.event.ForgeEventFactory.loadLootTable(ForgeEventFactory.java:653)
	at net.minecraftforge.common.ForgeHooks.loadLootTable(ForgeHooks.java:849)
	at net.minecraft.loot.LootTableManager.lambda$apply$0(LootTableManager.java:40)
	at java.util.HashMap.forEach(Unknown Source)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:38)
	at net.minecraft.loot.LootTableManager.func_212853_a_(LootTableManager.java:16)
	at net.minecraft.client.resources.ReloadListener.func_215269_a(SourceFile:13)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.postFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source)
	at net.minecraft.resources.AsyncReloader.func_219557_a(SourceFile:71)
	at net.minecraft.resources.AsyncReloader.func_219560_a(SourceFile:70)
	at java.util.concurrent.CompletableFuture$UniCompletion.claim(Unknown Source)
	at java.util.concurrent.CompletableFuture.uniAccept(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture.complete(Unknown Source)
	at net.minecraft.resources.AsyncReloader$1.func_216873_a(SourceFile:53)
	at net.minecraft.resources.AsyncReloader$1.func_216872_a(SourceFile:50)
	at java.util.concurrent.CompletableFuture.uniCompose(Unknown Source)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(Unknown Source)
	at java.util.concurrent.CompletableFuture.postComplete(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source)
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(Unknown Source)
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(Unknown Source)
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by TheMillman** [comment]
What version of forge and mod is it?
